### ISSUE TITLE
 download the files in the folder ‘model’

### ISSUE THREAD

**Issue by gaojianzhen** [QVPR/VPRTempo#14]
Hi, I can't download the files in the folder ‘model’, git lifs  can't use. Please tell me another way.

**Comment by AdamDHines** [comment]
Thanks for raising an issue. What exactly is the problem you're encountering with git lfs? It would be good to document in case others run into the same issue.

In the meantime, here is a Dropbox link to the models -> https://www.dropbox.com/scl/fi/ysfz7t7ek6h0pslwq9hd4/VPRTempo_pretrained_models.zip?rlkey=thg0rhn0hjsyov6zov63ni11o&st=h97p0ihe&dl=0

**Comment by AdamDHines** [comment]
Closing this as resolved. Please feel free to comment below what issue you had with git lfs.

**Comment by AdamDHines** [comment]
Dropbox download is now done automatically, please see https://github.com/QVPR/VPRTempo?tab=readme-ov-file#pretrained-models
